language: java
install: true
sudo: false
dist: trusty

jdk:
  - oraclejdk8

script:
  - ./gradlew build --stacktrace

before_install:
  - echo "$SIGNING_KEY_FILE_CONTENT" | base64 -d > $TRAVIS_BUILD_DIR/signing.key
  - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > $HOME/.npmrc

deploy:
  provider: script
  skip_cleanup: true
  script: ./gradlew publishAngularPlugin publishGradlePlugin publishMavenPlugin -PversionTag=$TRAVIS_TAG
  on:
    tags: true
    all_branches: true