language: java
install: true

jdk:
  - oraclejdk8

script:
  - ./gradlew build --stacktrace

before_install:
  - $SIGNING_KEY_FILE_CONTENT | base64 -d > $TRAVIS_BUILD_DIR/signing.key
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

deploy:
  provider: script
  script: ./gradlew publish -PtravisTag=$TRAVIS_TAG
  on:
    tags: true
    all_branches: true