language: java
install: true

jdk:
  - oraclejdk8

script:
  - ./gradlew build --stacktrace

deploy:
  provider: script
  script: ./gradlew publish -PtravisTag=$TRAVIS_TAG
  on:
    tags: true
    all_branches: true