version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - run: echo "$SIGNING_KEY_FILE_CONTENT" | base64 -d > ~/signing.key
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - checkout
      - run: ./gradlew build --stacktrace